[package]
name = "um"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = { version = "1.13.2", optional = true }

[features]
default = ["reclaim-memory"]
reclaim-memory = []
smallvec = ["dep:smallvec"]
